[2025-04-23T07:29:00.259+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T07:29:00.267+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_data.create_tables manual__2025-04-23T07:28:59.882567+00:00 [queued]>
[2025-04-23T07:29:00.270+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_data.create_tables manual__2025-04-23T07:28:59.882567+00:00 [queued]>
[2025-04-23T07:29:00.271+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-23T07:29:00.276+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): create_tables> on 2025-04-23 07:28:59.882567+00:00
[2025-04-23T07:29:00.282+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=15902) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T07:29:00.283+0000] {standard_task_runner.py:72} INFO - Started process 15904 to run task
[2025-04-23T07:29:00.284+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_data', 'create_tables', 'manual__2025-04-23T07:28:59.882567+00:00', '--job-id', '165', '--raw', '--subdir', 'DAGS_FOLDER/el_30min.py', '--cfg-path', '/tmp/tmp4od3xmy_']
[2025-04-23T07:29:00.285+0000] {standard_task_runner.py:105} INFO - Job 165: Subtask create_tables
[2025-04-23T07:29:00.305+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_weather_data.create_tables manual__2025-04-23T07:28:59.882567+00:00 [running]> on host eb276ba0497d
[2025-04-23T07:29:00.344+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_data' AIRFLOW_CTX_TASK_ID='create_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T07:28:59.882567+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T07:28:59.882567+00:00'
[2025-04-23T07:29:00.345+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T07:29:00.349+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-04-23T07:29:00.352+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-23T07:29:00.358+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T07:29:00.358+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fetch_weather_data, task_id=create_tables, run_id=manual__2025-04-23T07:28:59.882567+00:00, execution_date=20250423T072859, start_date=20250423T072900, end_date=20250423T072900
[2025-04-23T07:29:00.416+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T07:29:00.432+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-23T07:29:00.433+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
