[2025-04-23T11:05:17.166+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T11:05:17.176+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_transform.dbt_task_group.stg_weather_data_run manual__2025-04-23T10:57:01.209842+00:00 [queued]>
[2025-04-23T11:05:17.180+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_transform.dbt_task_group.stg_weather_data_run manual__2025-04-23T10:57:01.209842+00:00 [queued]>
[2025-04-23T11:05:17.180+0000] {taskinstance.py:2867} INFO - Starting attempt 5 of 7
[2025-04-23T11:05:17.185+0000] {taskinstance.py:2890} INFO - Executing <Task(DbtRunLocalOperator): dbt_task_group.stg_weather_data_run> on 2025-04-23 10:57:01.209842+00:00
[2025-04-23T11:05:17.193+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=14604) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T11:05:17.193+0000] {standard_task_runner.py:72} INFO - Started process 14674 to run task
[2025-04-23T11:05:17.194+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_transform', 'dbt_task_group.stg_weather_data_run', 'manual__2025-04-23T10:57:01.209842+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/dbtdag.py', '--cfg-path', '/tmp/tmpecf6bxlx']
[2025-04-23T11:05:17.194+0000] {standard_task_runner.py:105} INFO - Job 335: Subtask dbt_task_group.stg_weather_data_run
[2025-04-23T11:05:17.216+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_transform.dbt_task_group.stg_weather_data_run manual__2025-04-23T10:57:01.209842+00:00 [running]> on host eb276ba0497d
[2025-04-23T11:05:17.255+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_transform' AIRFLOW_CTX_TASK_ID='dbt_task_group.stg_weather_data_run' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T10:57:01.209842+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T10:57:01.209842+00:00'
[2025-04-23T11:05:17.257+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T11:05:17.258+0000] {local.py:213} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-04-23T11:05:17.259+0000] {local.py:416} INFO - Cloning project to writable temp directory /tmp/tmpqwtufsrd from /opt/airflow/dags/dbt/weather
[2025-04-23T11:05:17.259+0000] {local.py:427} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dbt_transform__dbt_task_group/target/partial_parse.msgpack
[2025-04-23T11:05:17.264+0000] {config.py:360} INFO - Profile caching is enable.
[2025-04-23T11:05:17.268+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-04-23T11:05:17.268+0000] {config.py:340} INFO - Profile found in cache using profile: /tmp/cosmos/profile/e6e13df970e8fe3ebb4d61c03236437e24a01a4909ada5aa9ec817ff39ff3ca3/profiles.yml.
[2025-04-23T11:05:17.271+0000] {runner.py:60} INFO - Trying to run dbtRunner with:
 ['deps', '--project-dir', '/tmp/tmpqwtufsrd', '--profiles-dir', '/tmp/cosmos/profile/e6e13df970e8fe3ebb4d61c03236437e24a01a4909ada5aa9ec817ff39ff3ca3', '--profile', 'default', '--target', 'dev']
 in /tmp/tmpqwtufsrd
[2025-04-23T11:05:17.278+0000] {logging_mixin.py:190} INFO - 11:05:17  Running with dbt=1.8.7
[2025-04-23T11:05:17.302+0000] {logging_mixin.py:190} INFO - 11:05:17  Installing dbt-labs/dbt_utils
[2025-04-23T11:05:18.095+0000] {logging_mixin.py:190} INFO - 11:05:18  Installed from version 0.9.6
[2025-04-23T11:05:18.095+0000] {logging_mixin.py:190} INFO - 11:05:18  Updated version available: 1.3.0
[2025-04-23T11:05:18.096+0000] {logging_mixin.py:190} INFO - 11:05:18
[2025-04-23T11:05:18.096+0000] {logging_mixin.py:190} INFO - 11:05:18  Updates available for packages: ['dbt-labs/dbt_utils']                 
Update your versions in packages.yml, then run dbt deps
[2025-04-23T11:05:19.044+0000] {runner.py:60} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'stg_weather_data', '--project-dir', '/tmp/tmpqwtufsrd', '--profiles-dir', '/tmp/cosmos/profile/e6e13df970e8fe3ebb4d61c03236437e24a01a4909ada5aa9ec817ff39ff3ca3', '--profile', 'default', '--target', 'dev']
 in /tmp/tmpqwtufsrd
[2025-04-23T11:05:19.048+0000] {logging_mixin.py:190} INFO - 11:05:19  Running with dbt=1.8.7
[2025-04-23T11:05:19.070+0000] {logging_mixin.py:190} INFO - 11:05:19  Registered adapter: postgres=1.9.0
[2025-04-23T11:05:19.100+0000] {logging_mixin.py:190} INFO - 11:05:19  Unable to do partial parsing because profile has changed
[2025-04-23T11:05:19.552+0000] {logging_mixin.py:190} INFO - 11:05:19  Found 5 models, 626 macros
[2025-04-23T11:05:19.553+0000] {logging_mixin.py:190} INFO - 11:05:19
[2025-04-23T11:05:19.594+0000] {logging_mixin.py:190} INFO - 11:05:19  Concurrency: 1 threads (target='dev')
[2025-04-23T11:05:19.595+0000] {logging_mixin.py:190} INFO - 11:05:19
[2025-04-23T11:05:19.596+0000] {logging_mixin.py:190} INFO - 11:05:19  1 of 1 START sql view model transformed.stg_weather_data ....................... [RUN]
[2025-04-23T11:05:19.832+0000] {logging_mixin.py:190} INFO - 11:05:19  1 of 1 OK created sql view model transformed.stg_weather_data .................. [CREATE VIEW in 0.24s]
[2025-04-23T11:05:19.837+0000] {logging_mixin.py:190} INFO - 11:05:19
[2025-04-23T11:05:19.838+0000] {logging_mixin.py:190} INFO - 11:05:19  Finished running 1 view model in 0 hours 0 minutes and 0.28 seconds (0.28s).
[2025-04-23T11:05:19.853+0000] {logging_mixin.py:190} INFO - 11:05:19
[2025-04-23T11:05:19.854+0000] {logging_mixin.py:190} INFO - 11:05:19  Completed successfully
[2025-04-23T11:05:19.854+0000] {logging_mixin.py:190} INFO - 11:05:19
[2025-04-23T11:05:19.854+0000] {logging_mixin.py:190} INFO - 11:05:19  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-04-23T11:05:20.876+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/cosmos/operators/local.py:616: UserWarning: The dataset URI postgres://192.168.88.40:9878/postgres.transformed.stg_weather_data is not AIP-60 compliant: URI format postgres:// must contain database, schema, and table names. In Airflow 3, this will raise an exception.
  datasets = [Dataset(uri) for uri in uris]

[2025-04-23T11:05:20.876+0000] {local.py:465} INFO - Inlets: []
[2025-04-23T11:05:20.876+0000] {local.py:466} INFO - Outlets: [Dataset(uri='postgres://192.168.88.40:9878/postgres.transformed.stg_weather_data', extra=None)]
[2025-04-23T11:05:20.876+0000] {local.py:656} INFO - Assigning inlets/outlets with DatasetAlias
[2025-04-23T11:05:20.901+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T11:05:20.901+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dbt_transform, task_id=dbt_task_group.stg_weather_data_run, run_id=manual__2025-04-23T10:57:01.209842+00:00, execution_date=20250423T105701, start_date=20250423T110517, end_date=20250423T110520
[2025-04-23T11:05:20.905+0000] {taskinstance.py:3064} INFO - Creating event for DatasetModel(uri='postgres://192.168.88.40:9878/postgres.transformed.stg_weather_data', extra={}) through aliases "dbt_transform__dbt_task_group__stg_weather_data_run"
[2025-04-23T11:05:20.973+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T11:05:20.988+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-23T11:05:20.989+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
