[2025-04-23T10:39:24.434+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T10:39:24.443+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_transform.dbt_task_group.stg_weather_data_run manual__2025-04-23T10:38:30.409166+00:00 [queued]>
[2025-04-23T10:39:24.447+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_transform.dbt_task_group.stg_weather_data_run manual__2025-04-23T10:38:30.409166+00:00 [queued]>
[2025-04-23T10:39:24.447+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 4
[2025-04-23T10:39:24.452+0000] {taskinstance.py:2890} INFO - Executing <Task(DbtRunLocalOperator): dbt_task_group.stg_weather_data_run> on 2025-04-23 10:38:30.409166+00:00
[2025-04-23T10:39:24.459+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=11853) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T10:39:24.460+0000] {standard_task_runner.py:72} INFO - Started process 11923 to run task
[2025-04-23T10:39:24.460+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_transform', 'dbt_task_group.stg_weather_data_run', 'manual__2025-04-23T10:38:30.409166+00:00', '--job-id', '300', '--raw', '--subdir', 'DAGS_FOLDER/dbtdag.py', '--cfg-path', '/tmp/tmpcosaudaj']
[2025-04-23T10:39:24.461+0000] {standard_task_runner.py:105} INFO - Job 300: Subtask dbt_task_group.stg_weather_data_run
[2025-04-23T10:39:24.480+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_transform.dbt_task_group.stg_weather_data_run manual__2025-04-23T10:38:30.409166+00:00 [running]> on host eb276ba0497d
[2025-04-23T10:39:24.517+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_transform' AIRFLOW_CTX_TASK_ID='dbt_task_group.stg_weather_data_run' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T10:38:30.409166+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T10:38:30.409166+00:00'
[2025-04-23T10:39:24.518+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T10:39:24.519+0000] {local.py:213} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-04-23T10:39:24.520+0000] {local.py:416} INFO - Cloning project to writable temp directory /tmp/tmprzzp8e46 from /opt/airflow/dags/dbt/weather
[2025-04-23T10:39:24.520+0000] {local.py:427} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dbt_transform__dbt_task_group/target/partial_parse.msgpack
[2025-04-23T10:39:24.525+0000] {config.py:360} INFO - Profile caching is enable.
[2025-04-23T10:39:24.529+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-04-23T10:39:24.529+0000] {config.py:340} INFO - Profile found in cache using profile: /tmp/cosmos/profile/e6e13df970e8fe3ebb4d61c03236437e24a01a4909ada5aa9ec817ff39ff3ca3/profiles.yml.
[2025-04-23T10:39:24.532+0000] {runner.py:60} INFO - Trying to run dbtRunner with:
 ['deps', '--project-dir', '/tmp/tmprzzp8e46', '--profiles-dir', '/tmp/cosmos/profile/e6e13df970e8fe3ebb4d61c03236437e24a01a4909ada5aa9ec817ff39ff3ca3', '--profile', 'default', '--target', 'dev']
 in /tmp/tmprzzp8e46
[2025-04-23T10:39:24.538+0000] {logging_mixin.py:190} INFO - 10:39:24  Running with dbt=1.8.7
[2025-04-23T10:39:24.559+0000] {logging_mixin.py:190} INFO - 10:39:24  Installing dbt-labs/dbt_utils
[2025-04-23T10:39:25.454+0000] {logging_mixin.py:190} INFO - 10:39:25  Installed from version 0.9.6
[2025-04-23T10:39:25.454+0000] {logging_mixin.py:190} INFO - 10:39:25  Updated version available: 1.3.0
[2025-04-23T10:39:25.455+0000] {logging_mixin.py:190} INFO - 10:39:25
[2025-04-23T10:39:25.455+0000] {logging_mixin.py:190} INFO - 10:39:25  Updates available for packages: ['dbt-labs/dbt_utils']                 
Update your versions in packages.yml, then run dbt deps
[2025-04-23T10:39:26.374+0000] {runner.py:60} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'stg_weather_data', '--project-dir', '/tmp/tmprzzp8e46', '--profiles-dir', '/tmp/cosmos/profile/e6e13df970e8fe3ebb4d61c03236437e24a01a4909ada5aa9ec817ff39ff3ca3', '--profile', 'default', '--target', 'dev']
 in /tmp/tmprzzp8e46
[2025-04-23T10:39:26.378+0000] {logging_mixin.py:190} INFO - 10:39:26  Running with dbt=1.8.7
[2025-04-23T10:39:26.400+0000] {logging_mixin.py:190} INFO - 10:39:26  Registered adapter: postgres=1.9.0
[2025-04-23T10:39:26.435+0000] {logging_mixin.py:190} INFO - 10:39:26  Unable to do partial parsing because profile has changed
[2025-04-23T10:39:26.904+0000] {logging_mixin.py:190} INFO - 10:39:26  Found 5 models, 626 macros
[2025-04-23T10:39:26.906+0000] {logging_mixin.py:190} INFO - 10:39:26
[2025-04-23T10:39:26.947+0000] {logging_mixin.py:190} INFO - 10:39:26  Concurrency: 1 threads (target='dev')
[2025-04-23T10:39:26.948+0000] {logging_mixin.py:190} INFO - 10:39:26
[2025-04-23T10:39:26.949+0000] {logging_mixin.py:190} INFO - 10:39:26  1 of 1 START sql view model transformed.stg_weather_data ....................... [RUN]
[2025-04-23T10:39:27.003+0000] {logging_mixin.py:190} INFO - 10:39:27  1 of 1 OK created sql view model transformed.stg_weather_data .................. [CREATE VIEW in 0.05s]
[2025-04-23T10:39:27.008+0000] {logging_mixin.py:190} INFO - 10:39:27
[2025-04-23T10:39:27.008+0000] {logging_mixin.py:190} INFO - 10:39:27  Finished running 1 view model in 0 hours 0 minutes and 0.10 seconds (0.10s).
[2025-04-23T10:39:27.205+0000] {logging_mixin.py:190} INFO - 10:39:27
[2025-04-23T10:39:27.205+0000] {logging_mixin.py:190} INFO - 10:39:27  Completed successfully
[2025-04-23T10:39:27.206+0000] {logging_mixin.py:190} INFO - 10:39:27
[2025-04-23T10:39:27.206+0000] {logging_mixin.py:190} INFO - 10:39:27  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-04-23T10:39:28.295+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/cosmos/operators/local.py:616: UserWarning: The dataset URI postgres://192.168.88.40:9878/postgres.transformed.stg_weather_data is not AIP-60 compliant: URI format postgres:// must contain database, schema, and table names. In Airflow 3, this will raise an exception.
  datasets = [Dataset(uri) for uri in uris]

[2025-04-23T10:39:28.295+0000] {local.py:465} INFO - Inlets: []
[2025-04-23T10:39:28.295+0000] {local.py:466} INFO - Outlets: [Dataset(uri='postgres://192.168.88.40:9878/postgres.transformed.stg_weather_data', extra=None)]
[2025-04-23T10:39:28.295+0000] {local.py:656} INFO - Assigning inlets/outlets with DatasetAlias
[2025-04-23T10:39:28.319+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T10:39:28.319+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dbt_transform, task_id=dbt_task_group.stg_weather_data_run, run_id=manual__2025-04-23T10:38:30.409166+00:00, execution_date=20250423T103830, start_date=20250423T103924, end_date=20250423T103928
[2025-04-23T10:39:28.324+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/datasets/manager.py:68: UserWarning: The dataset URI postgres://192.168.88.40:9878/postgres.transformed.stg_weather_data is not AIP-60 compliant: URI format postgres:// must contain database, schema, and table names. In Airflow 3, this will raise an exception.
  self.notify_dataset_created(dataset=Dataset(uri=dataset_model.uri, extra=dataset_model.extra))

[2025-04-23T10:39:28.324+0000] {taskinstance.py:3054} WARNING - Created a new DatasetModel(uri='postgres://192.168.88.40:9878/postgres.transformed.stg_weather_data', extra={}) as it did not exist.
[2025-04-23T10:39:28.327+0000] {taskinstance.py:3064} INFO - Creating event for DatasetModel(uri='postgres://192.168.88.40:9878/postgres.transformed.stg_weather_data', extra={}) through aliases "dbt_transform__dbt_task_group__stg_weather_data_run"
[2025-04-23T10:39:28.401+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T10:39:28.416+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-23T10:39:28.417+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
