[2025-04-23T09:23:16.477+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T09:23:16.489+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_data_daily.check_table_and_decide manual__2025-04-23T09:23:13.048401+00:00 [queued]>
[2025-04-23T09:23:16.494+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_data_daily.check_table_and_decide manual__2025-04-23T09:23:13.048401+00:00 [queued]>
[2025-04-23T09:23:16.494+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-23T09:23:17.714+0000] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): check_table_and_decide> on 2025-04-23 09:23:13.048401+00:00
[2025-04-23T09:23:17.722+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4253) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T09:23:17.723+0000] {standard_task_runner.py:72} INFO - Started process 4271 to run task
[2025-04-23T09:23:17.723+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_data_daily', 'check_table_and_decide', 'manual__2025-04-23T09:23:13.048401+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/el_daily.py', '--cfg-path', '/tmp/tmp9m1v9n8a']
[2025-04-23T09:23:17.725+0000] {standard_task_runner.py:105} INFO - Job 197: Subtask check_table_and_decide
[2025-04-23T09:23:17.895+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_weather_data_daily.check_table_and_decide manual__2025-04-23T09:23:13.048401+00:00 [running]> on host eb276ba0497d
[2025-04-23T09:23:18.725+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_data_daily' AIRFLOW_CTX_TASK_ID='check_table_and_decide' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T09:23:13.048401+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T09:23:13.048401+00:00'
[2025-04-23T09:23:18.727+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T09:23:18.728+0000] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-04-23T09:23:18.728+0000] {python.py:240} INFO - Done. Returned value was: {{ task_instance.xcom_pull(task_ids='check_if_table_exists', dag_id='adhoc_airflow', key='return_value') }}
[2025-04-23T09:23:18.729+0000] {branch.py:38} INFO - Branch into {{ task_instance.xcom_pull(task_ids='check_if_table_exists', dag_id='adhoc_airflow', key='return_value') }}
[2025-04-23T09:23:18.729+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/branch.py", line 40, in do_branch
    self.skip_all_except(context["ti"], branch_task_ids)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 191, in skip_all_except
    branch_task_ids = list(branch_task_ids)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/branch.py", line 60, in _expand_task_group_roots
    for branch in branches_to_execute:
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 329, in __iter__
    raise TypeError("'XComArg' object is not iterable")
TypeError: 'XComArg' object is not iterable
[2025-04-23T09:23:18.735+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_weather_data_daily, task_id=check_table_and_decide, run_id=manual__2025-04-23T09:23:13.048401+00:00, execution_date=20250423T092313, start_date=20250423T092316, end_date=20250423T092318
[2025-04-23T09:23:19.646+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T09:23:19.646+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 197 for task check_table_and_decide ('XComArg' object is not iterable; 4271)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/branch.py", line 40, in do_branch
    self.skip_all_except(context["ti"], branch_task_ids)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 191, in skip_all_except
    branch_task_ids = list(branch_task_ids)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/branch.py", line 60, in _expand_task_group_roots
    for branch in branches_to_execute:
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom_arg.py", line 329, in __iter__
    raise TypeError("'XComArg' object is not iterable")
TypeError: 'XComArg' object is not iterable
[2025-04-23T09:23:19.660+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-23T09:23:19.665+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
