[2025-04-23T09:31:01.488+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T09:31:01.498+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_data_daily.branch_table_check manual__2025-04-23T09:31:00.792292+00:00 [queued]>
[2025-04-23T09:31:01.502+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_data_daily.branch_table_check manual__2025-04-23T09:31:00.792292+00:00 [queued]>
[2025-04-23T09:31:01.502+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-23T09:31:01.508+0000] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): branch_table_check> on 2025-04-23 09:31:00.792292+00:00
[2025-04-23T09:31:01.514+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5252) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T09:31:01.515+0000] {standard_task_runner.py:72} INFO - Started process 5254 to run task
[2025-04-23T09:31:01.515+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_data_daily', 'branch_table_check', 'manual__2025-04-23T09:31:00.792292+00:00', '--job-id', '221', '--raw', '--subdir', 'DAGS_FOLDER/el_daily.py', '--cfg-path', '/tmp/tmp7xpanbwb']
[2025-04-23T09:31:01.517+0000] {standard_task_runner.py:105} INFO - Job 221: Subtask branch_table_check
[2025-04-23T09:31:01.540+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_weather_data_daily.branch_table_check manual__2025-04-23T09:31:00.792292+00:00 [running]> on host eb276ba0497d
[2025-04-23T09:31:01.576+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_data_daily' AIRFLOW_CTX_TASK_ID='branch_table_check' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T09:31:00.792292+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T09:31:00.792292+00:00'
[2025-04-23T09:31:01.577+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T09:31:01.578+0000] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-04-23T09:31:01.582+0000] {python.py:240} INFO - Done. Returned value was: extract_backfill_data
[2025-04-23T09:31:01.582+0000] {branch.py:38} INFO - Branch into extract_backfill_data
[2025-04-23T09:31:01.582+0000] {skipmixin.py:233} INFO - Following branch ('extract_backfill_data',)
[2025-04-23T09:31:01.587+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/branch.py", line 40, in do_branch
    self.skip_all_except(context["ti"], branch_task_ids)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 192, in skip_all_except
    SkipMixin._skip_all_except(ti=ti, branch_task_ids=branch_task_ids)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 246, in _skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'extract_backfill_data'}.
[2025-04-23T09:31:01.590+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=fetch_weather_data_daily, task_id=branch_table_check, run_id=manual__2025-04-23T09:31:00.792292+00:00, execution_date=20250423T093100, start_date=20250423T093101, end_date=20250423T093101
[2025-04-23T09:31:01.601+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T09:31:01.601+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 221 for task branch_table_check ('branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'extract_backfill_data'}.; 5254)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/branch.py", line 40, in do_branch
    self.skip_all_except(context["ti"], branch_task_ids)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 192, in skip_all_except
    SkipMixin._skip_all_except(ti=ti, branch_task_ids=branch_task_ids)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/api_internal/internal_api_call.py", line 166, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/skipmixin.py", line 246, in _skip_all_except
    raise AirflowException(
airflow.exceptions.AirflowException: 'branch_task_ids' must contain only valid task_ids. Invalid tasks found: {'extract_backfill_data'}.
[2025-04-23T09:31:01.648+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-23T09:31:01.661+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T09:31:01.661+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
