[2025-04-23T10:46:50.728+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T10:46:50.738+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_transform.dbt_task_group.stg_weather_data_run manual__2025-04-23T10:46:42.794055+00:00 [queued]>
[2025-04-23T10:46:50.742+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_transform.dbt_task_group.stg_weather_data_run manual__2025-04-23T10:46:42.794055+00:00 [queued]>
[2025-04-23T10:46:50.742+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-04-23T10:46:50.749+0000] {taskinstance.py:2890} INFO - Executing <Task(DbtRunLocalOperator): dbt_task_group.stg_weather_data_run> on 2025-04-23 10:46:42.794055+00:00
[2025-04-23T10:46:50.757+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=12537) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T10:46:50.757+0000] {standard_task_runner.py:72} INFO - Started process 12605 to run task
[2025-04-23T10:46:50.758+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dbt_transform', 'dbt_task_group.stg_weather_data_run', 'manual__2025-04-23T10:46:42.794055+00:00', '--job-id', '305', '--raw', '--subdir', 'DAGS_FOLDER/dbtdag.py', '--cfg-path', '/tmp/tmp7wkr3irn']
[2025-04-23T10:46:50.758+0000] {standard_task_runner.py:105} INFO - Job 305: Subtask dbt_task_group.stg_weather_data_run
[2025-04-23T10:46:50.781+0000] {task_command.py:467} INFO - Running <TaskInstance: dbt_transform.dbt_task_group.stg_weather_data_run manual__2025-04-23T10:46:42.794055+00:00 [running]> on host eb276ba0497d
[2025-04-23T10:46:50.821+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_transform' AIRFLOW_CTX_TASK_ID='dbt_task_group.stg_weather_data_run' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T10:46:42.794055+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T10:46:42.794055+00:00'
[2025-04-23T10:46:50.823+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T10:46:50.824+0000] {local.py:213} INFO - dbtRunner is available. Using dbtRunner for invoking dbt.
[2025-04-23T10:46:50.824+0000] {local.py:416} INFO - Cloning project to writable temp directory /tmp/tmpgbtv2wzy from /opt/airflow/dags/dbt/weather
[2025-04-23T10:46:50.825+0000] {local.py:427} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/dbt_transform__dbt_task_group/target/partial_parse.msgpack
[2025-04-23T10:46:50.830+0000] {config.py:360} INFO - Profile caching is enable.
[2025-04-23T10:46:50.835+0000] {base.py:84} INFO - Retrieving connection 'postgres'
[2025-04-23T10:46:50.835+0000] {config.py:340} INFO - Profile found in cache using profile: /tmp/cosmos/profile/e6e13df970e8fe3ebb4d61c03236437e24a01a4909ada5aa9ec817ff39ff3ca3/profiles.yml.
[2025-04-23T10:46:50.837+0000] {runner.py:60} INFO - Trying to run dbtRunner with:
 ['deps', '--project-dir', '/tmp/tmpgbtv2wzy', '--profiles-dir', '/tmp/cosmos/profile/e6e13df970e8fe3ebb4d61c03236437e24a01a4909ada5aa9ec817ff39ff3ca3', '--profile', 'default', '--target', 'dev']
 in /tmp/tmpgbtv2wzy
[2025-04-23T10:46:50.844+0000] {logging_mixin.py:190} INFO - 10:46:50  Running with dbt=1.8.7
[2025-04-23T10:46:50.869+0000] {logging_mixin.py:190} INFO - 10:46:50  Installing dbt-labs/dbt_utils
[2025-04-23T10:46:51.688+0000] {logging_mixin.py:190} INFO - 10:46:51  Installed from version 0.9.6
[2025-04-23T10:46:51.688+0000] {logging_mixin.py:190} INFO - 10:46:51  Updated version available: 1.3.0
[2025-04-23T10:46:51.689+0000] {logging_mixin.py:190} INFO - 10:46:51
[2025-04-23T10:46:51.690+0000] {logging_mixin.py:190} INFO - 10:46:51  Updates available for packages: ['dbt-labs/dbt_utils']                 
Update your versions in packages.yml, then run dbt deps
[2025-04-23T10:46:52.624+0000] {runner.py:60} INFO - Trying to run dbtRunner with:
 ['run', '--models', 'stg_weather_data', '--project-dir', '/tmp/tmpgbtv2wzy', '--profiles-dir', '/tmp/cosmos/profile/e6e13df970e8fe3ebb4d61c03236437e24a01a4909ada5aa9ec817ff39ff3ca3', '--profile', 'default', '--target', 'dev']
 in /tmp/tmpgbtv2wzy
[2025-04-23T10:46:52.628+0000] {logging_mixin.py:190} INFO - 10:46:52  Running with dbt=1.8.7
[2025-04-23T10:46:52.649+0000] {logging_mixin.py:190} INFO - 10:46:52  Registered adapter: postgres=1.9.0
[2025-04-23T10:46:52.682+0000] {logging_mixin.py:190} INFO - 10:46:52  Unable to do partial parsing because profile has changed
[2025-04-23T10:46:53.137+0000] {logging_mixin.py:190} INFO - 10:46:53  Found 5 models, 626 macros
[2025-04-23T10:46:53.139+0000] {logging_mixin.py:190} INFO - 10:46:53
[2025-04-23T10:46:53.179+0000] {logging_mixin.py:190} INFO - 10:46:53  Concurrency: 1 threads (target='dev')
[2025-04-23T10:46:53.179+0000] {logging_mixin.py:190} INFO - 10:46:53
[2025-04-23T10:46:53.181+0000] {logging_mixin.py:190} INFO - 10:46:53  1 of 1 START sql view model transformed.stg_weather_data ....................... [RUN]
[2025-04-23T10:46:53.428+0000] {logging_mixin.py:190} INFO - 10:46:53  1 of 1 OK created sql view model transformed.stg_weather_data .................. [CREATE VIEW in 0.25s]
[2025-04-23T10:46:53.434+0000] {logging_mixin.py:190} INFO - 10:46:53
[2025-04-23T10:46:53.435+0000] {logging_mixin.py:190} INFO - 10:46:53  Finished running 1 view model in 0 hours 0 minutes and 0.30 seconds (0.30s).
[2025-04-23T10:46:53.453+0000] {logging_mixin.py:190} INFO - 10:46:53
[2025-04-23T10:46:53.453+0000] {logging_mixin.py:190} INFO - 10:46:53  Completed successfully
[2025-04-23T10:46:53.453+0000] {logging_mixin.py:190} INFO - 10:46:53
[2025-04-23T10:46:53.454+0000] {logging_mixin.py:190} INFO - 10:46:53  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2025-04-23T10:46:54.445+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/cosmos/operators/local.py:616: UserWarning: The dataset URI postgres://192.168.88.40:9878/postgres.transformed.stg_weather_data is not AIP-60 compliant: URI format postgres:// must contain database, schema, and table names. In Airflow 3, this will raise an exception.
  datasets = [Dataset(uri) for uri in uris]

[2025-04-23T10:46:54.445+0000] {local.py:465} INFO - Inlets: []
[2025-04-23T10:46:54.445+0000] {local.py:466} INFO - Outlets: [Dataset(uri='postgres://192.168.88.40:9878/postgres.transformed.stg_weather_data', extra=None)]
[2025-04-23T10:46:54.446+0000] {local.py:656} INFO - Assigning inlets/outlets with DatasetAlias
[2025-04-23T10:46:54.471+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T10:46:54.471+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dbt_transform, task_id=dbt_task_group.stg_weather_data_run, run_id=manual__2025-04-23T10:46:42.794055+00:00, execution_date=20250423T104642, start_date=20250423T104650, end_date=20250423T104654
[2025-04-23T10:46:54.475+0000] {taskinstance.py:3064} INFO - Creating event for DatasetModel(uri='postgres://192.168.88.40:9878/postgres.transformed.stg_weather_data', extra={}) through aliases "dbt_transform__dbt_task_group__stg_weather_data_run"
[2025-04-23T10:46:54.538+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T10:46:54.553+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-23T10:46:54.554+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
