[2025-04-23T23:15:01.639+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T23:15:01.648+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_weather_data_daily.check_if_table_exists scheduled__2025-04-22T23:15:00+00:00 [queued]>
[2025-04-23T23:15:01.652+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_weather_data_daily.check_if_table_exists scheduled__2025-04-22T23:15:00+00:00 [queued]>
[2025-04-23T23:15:01.652+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-23T23:15:01.659+0000] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): check_if_table_exists> on 2025-04-22 23:15:00+00:00
[2025-04-23T23:15:01.665+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=68972) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-23T23:15:01.666+0000] {standard_task_runner.py:72} INFO - Started process 68974 to run task
[2025-04-23T23:15:01.667+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_weather_data_daily', 'check_if_table_exists', 'scheduled__2025-04-22T23:15:00+00:00', '--job-id', '346', '--raw', '--subdir', 'DAGS_FOLDER/el_daily.py', '--cfg-path', '/tmp/tmp38186oes']
[2025-04-23T23:15:01.668+0000] {standard_task_runner.py:105} INFO - Job 346: Subtask check_if_table_exists
[2025-04-23T23:15:01.692+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_weather_data_daily.check_if_table_exists scheduled__2025-04-22T23:15:00+00:00 [running]> on host eb276ba0497d
[2025-04-23T23:15:01.731+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_weather_data_daily' AIRFLOW_CTX_TASK_ID='check_if_table_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-04-22T23:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-22T23:15:00+00:00'
[2025-04-23T23:15:01.732+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-23T23:15:01.733+0000] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-04-23T23:15:01.737+0000] {python.py:240} INFO - Done. Returned value was: extract_today_branch
[2025-04-23T23:15:01.737+0000] {branch.py:38} INFO - Branch into extract_today_branch
[2025-04-23T23:15:01.737+0000] {skipmixin.py:233} INFO - Following branch ('extract_today_branch',)
[2025-04-23T23:15:01.743+0000] {skipmixin.py:281} INFO - Skipping tasks [('extract_backfill_branch', -1)]
[2025-04-23T23:15:01.758+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-23T23:15:01.758+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fetch_weather_data_daily, task_id=check_if_table_exists, run_id=scheduled__2025-04-22T23:15:00+00:00, execution_date=20250422T231500, start_date=20250423T231501, end_date=20250423T231501
[2025-04-23T23:15:01.799+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T23:15:01.815+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-23T23:15:01.816+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
